### ISSUE TITLE
BirdHouse Twitter Authorization Error(Cannot get access token) (Solved)

### ISSUE THREAD

**Issue by nyus** [jpurcell/birdhouse#24]
Hey Joe,
I am currently using your code to make Twitter authorizing. I am using Titanium to develop Android app. Titanium mobile SDK is 1.7.1.

So the problem is: the code gets stucked before it has the chance to call function save_access_token(), namely,

```
       XHR.onload = function() {

        // execute the callback function
        if (typeof(callback)=='function') {
            callback(XHR.responseText);
        }

        return XHR.responseText;
       };
```

is not entered ( inside function api(), around line 510). And the error from logcat says the following:

D/TiHttpClient( 4094): (kroll$4: app://windows/Home/profile.js) [2,79903] Setting ready state to 1
I/TiHttpClient( 4094): (kroll$4: app://windows/Home/profile.js) [2,79905] Twitter: not sending X-Requested-With header
D/TiHttpClient( 4094): (TiHttpClient-6) [1132,81042] Setting ready state to 2
D/TiHttpClient( 4094): (TiHttpClient-6) [2,81044] Setting ready state to 3
D/TiHttpClient( 4094): (TiHttpClient-6) [10,81054] Setting ready state to 4
W/MessageQueue( 4094): Handler{449afa78} sending message to a Handler on a dead thread
W/MessageQueue( 4094): java.lang.RuntimeException: Handler{449afa78} sending message to a Handler on a dead thread
W/MessageQueue( 4094): at android.os.MessageQueue.enqueueMessage(MessageQueue.java:179)
W/MessageQueue( 4094): at android.os.Handler.sendMessageAtTime(Handler.java:457)
W/MessageQueue( 4094): at android.os.Handler.sendMessageDelayed(Handler.java:430)
W/MessageQueue( 4094): at android.os.Handler.post(Handler.java:248)
W/MessageQueue( 4094): at org.appcelerator.titanium.kroll.KrollCallback.callAsync(KrollCallback.java:162)
W/MessageQueue( 4094): at org.appcelerator.titanium.kroll.KrollCallback.callAsync(KrollCallback.java:96)
W/MessageQueue( 4094): at org.appcelerator.titanium.kroll.KrollCallback.callAsync(KrollCallback.java:91)
W/MessageQueue( 4094): at ti.modules.titanium.network.TiHTTPClient.fireCallback(TiHTTPClient.java:483)
W/MessageQueue( 4094): at ti.modules.titanium.network.TiHTTPClient.fireCallback(TiHTTPClient.java:474)
W/MessageQueue( 4094): at ti.modules.titanium.network.TiHTTPClient.setReadyState(TiHTTPClient.java:506)
W/MessageQueue( 4094): at ti.modules.titanium.network.TiHTTPClient$ClientRunnable.run(TiHTTPClient.java:1022)
W/MessageQueue( 4094): at java.lang.Thread.run(Thread.java:1096)

Do you have any idea how to fix this???? Thank you so much!!!!!

Jason

**Comment by nyus** [comment]
I saw a post in Issue section and found the solution here:https://github.com/jpurcell/birdhouse/issues/9
Thanks to @jgoslin. 
solution is inside function function get_request_verifier(callback) {}

if (Ti.Platform.osname=='iphone' && cfg.show_login_toolbar) {
var win = Ti.UI.createWindow({
top: 0,
modal: true,
fullscreen: true
});
........
}else{
var win = Ti.UI.createWindow({
top: 0
});

```
 }
```

}
